# Archive once NA fill is confirmed

In [8]:
import pandas as pd

In [9]:
df_1 = pd.read_csv('/global/scratch/users/yougsanghvi/aggregated_results_era5_usa/era5_usa_agg_fillna1979.csv')
df_2 = pd.read_csv('/global/scratch/users/yougsanghvi/aggregated_results_era5_usa/era5_usa_agg_1979.csv')

In [10]:
combined_df = pd.concat([df_1, df_2], ignore_index=True)

In [15]:
print(df.isna().sum())

year        0
month       3
poly_id     0
order_1    39
order_2    39
order_3    39
order_4    39
dtype: int64

In [13]:
na_rows = combined_df[combined_df.isna().any(axis=1)]
print(na_rows)

       year  month  poly_id     order_1       order_2        order_3  \
0      1979    NaN    15003         NaN           NaN            NaN
1      1979    1.0    15003  665.422516  14310.997438  308360.783622
2      1979    2.0    15003  596.125690  12716.184927  271751.357387
3      1979    3.0    15003  672.251034  14590.996684  316968.953301
4      1979    4.0    15003  664.050024  14708.669638  326012.244336
...     ...    ...      ...         ...           ...            ...
73740  1979    8.0    69110         NaN           NaN            NaN
73741  1979    9.0    69110         NaN           NaN            NaN
73742  1979   10.0    69110         NaN           NaN            NaN
73743  1979   11.0    69110         NaN           NaN            NaN
73744  1979   12.0    69110         NaN           NaN            NaN

            order_4  order_1_avg  order_2_avg  order_3_avg  order_4_avg
0               NaN          NaN          NaN          NaN          NaN
1      6.656519e+06          NaN          NaN          NaN          NaN
2      5.817572e+06          NaN          NaN          NaN          NaN
3      6.891621e+06          NaN          NaN          NaN          NaN
4      7.230648e+06          NaN          NaN          NaN          NaN
...             ...          ...          ...          ...          ...
73740           NaN          NaN          NaN          NaN          NaN
73741           NaN          NaN          NaN          NaN          NaN
73742           NaN          NaN          NaN          NaN          NaN
73743           NaN          NaN          NaN          NaN          NaN
73744           NaN          NaN          NaN          NaN          NaN

[36173 rows x 11 columns]

In [14]:
print(len(na_rows))

36173

In [12]:
# filter only Na values
df_na = df[combined_df['order_1'].isna()]
df_na

/tmp/ipykernel_4160848/3856214160.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_na = df[combined_df['order_1'].isna()]

       year  month  poly_id  order_1  order_2  order_3  order_4
0      1979    NaN    15003      NaN      NaN      NaN      NaN
13     1979    1.0    60040      NaN      NaN      NaN      NaN
14     1979    2.0    60040      NaN      NaN      NaN      NaN
15     1979    3.0    60040      NaN      NaN      NaN      NaN
16     1979    4.0    60040      NaN      NaN      NaN      NaN
17     1979    5.0    60040      NaN      NaN      NaN      NaN
18     1979    6.0    60040      NaN      NaN      NaN      NaN
19     1979    7.0    60040      NaN      NaN      NaN      NaN
20     1979    8.0    60040      NaN      NaN      NaN      NaN
21     1979    9.0    60040      NaN      NaN      NaN      NaN
22     1979   10.0    60040      NaN      NaN      NaN      NaN
23     1979   11.0    60040      NaN      NaN      NaN      NaN
24     1979   12.0    60040      NaN      NaN      NaN      NaN
61     1979    1.0    60030      NaN      NaN      NaN      NaN
62     1979    2.0    60030      NaN      NaN      NaN      NaN
63     1979    3.0    60030      NaN      NaN      NaN      NaN
64     1979    4.0    60030      NaN      NaN      NaN      NaN
65     1979    5.0    60030      NaN      NaN      NaN      NaN
66     1979    6.0    60030      NaN      NaN      NaN      NaN
67     1979    7.0    60030      NaN      NaN      NaN      NaN
68     1979    8.0    60030      NaN      NaN      NaN      NaN
69     1979    9.0    60030      NaN      NaN      NaN      NaN
70     1979   10.0    60030      NaN      NaN      NaN      NaN
71     1979   11.0    60030      NaN      NaN      NaN      NaN
72     1979   12.0    60030      NaN      NaN      NaN      NaN
11629  1979    NaN    27077      NaN      NaN      NaN      NaN
34958  1979    1.0    69085      NaN      NaN      NaN      NaN
34959  1979    2.0    69085      NaN      NaN      NaN      NaN
34960  1979    3.0    69085      NaN      NaN      NaN      NaN
34961  1979    4.0    69085      NaN      NaN      NaN      NaN
34962  1979    5.0    69085      NaN      NaN      NaN      NaN
34963  1979    6.0    69085      NaN      NaN      NaN      NaN
34964  1979    7.0    69085      NaN      NaN      NaN      NaN
34965  1979    8.0    69085      NaN      NaN      NaN      NaN
34966  1979    9.0    69085      NaN      NaN      NaN      NaN
34967  1979   10.0    69085      NaN      NaN      NaN      NaN
34968  1979   11.0    69085      NaN      NaN      NaN      NaN
34969  1979   12.0    69085      NaN      NaN      NaN      NaN
35006  1979    NaN    69085      NaN      NaN      NaN      NaN

In [7]:
filtered_df = df[df["poly_id"] == 15003]
filtered_df

,year,month,poly_id,order_1,order_2,order_3,order_4
0,1979,NaN,15003,NaN,NaN,NaN,NaN
1,1979,1.0,15003,665.422516,14310.997438,308360.783622,6.656519e+06
2,1979,2.0,15003,596.125690,12716.184927,271751.357387,5.817572e+06
3,1979,3.0,15003,672.251034,14590.996684,316968.953301,6.891621e+06
4,1979,4.0,15003,664.050024,14708.669638,326012.244336,7.230648e+06
5,1979,5.0,15003,720.255402,16741.986720,389332.822445,9.057879e+06
6,1979,6.0,15003,716.883162,17133.271887,409540.544387,9.790797e+06
7,1979,7.0,15003,762.945805,18782.271355,462513.248071,1.139255e+07
8,1979,8.0,15003,785.149929,19893.142421,504213.032933,1.278453e+07
9,1979,9.0,15003,765.582520,19540.788838,498851.088413,1.273732e+07
10,1979,10.0,15003,781.868975,19728.050998,497978.066624,1.257506e+07
11,1979,11.0,15003,718.171705,17212.348998,412989.114043,9.919878e+06
12,1979,12.0,15003,718.396410,16680.210272,388014.238532,9.042248e+06